Update dependencies (#169)
* ci: Raise supported Node.js versions

15.x is the first branch that came with npm 7, which supports the new lockfile schema we are soon going to upgrade to.
14.x is still supported but only for next two weeks so let's not bother.

* Update lockfile

Also jump to version 3.

* Update Webpack

This will be required to avoid conflicts with testing-library.

* Upgrade Babel and dependent parts of the toolchain

Had to fix a few errors now reported by eslint:

    src/__tests__/createManager.test.js
      1:12  error  'Promise' is already defined as a built-in global variable  no-redeclare
    dist/Button.js
      4:34  error  '_setPrototypeOf' is a function  no-func-assign
    src/specialAssign.js
      5:12  error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins

Then some update Jest snapshots to match the current serialization.
As well as resolve some other issues with Jest:

    FAIL  src/__tests__/createManager.test.js
     ● Test suite failed to run

       The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
       Consider using the "jsdom" test environment.

       ReferenceError: document is not defined
    FAIL  src/__tests__/Menu.test.js
     ● <Menu> › menu updating

       It looks like you called `mount()` without a global document being loaded.

* Format the code and update prettier

The changes are not actually from the update – it looks like we just forgot to format the codebase in the past.

* Update husky to a version that does not auto-install hooks

That was super confusing:
https://blog.typicode.com/husky-git-hooks-autoinstall/

Add a `prepare` script instead as recommended by the article.